### ISSUE TITLE
Personal Details Tab/Kyc

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#13]
-	Phone number accepts non-numbers. Missing validation.
-	Years of services takes negative values
-	Personal details data does not show the updated values,
o	Select a broker
o	Upload required images
o	Update personal details and click next
o	Click back to verify the data updated
o	The profile data is previous data and not the latest updated data for fields FN, LN and PhoneNumber.
-	Estimated Liquid Assets, Experience in Securities, Experience in derivatives and Annual income takes negative values.
-	Missing timeZone field
-	Change to text box for address fields

Screen details
1) Chrome
2) 1366 X 768

**Comment by shastri9999** [comment]
@suneelng 
1. For field validations taking only positive number for fields like Years of Services, Please pass additional info in the validation type, currently it just says NUMBER, can you change this to POSITIVE_NUMBER ? Basically need an indication to know only positive values are allowed. Let me know what can be used.
2. For address fields change the type to textarea, the code wont be able to distinguish between normal text and address otherwise

**Comment by suneelng** [comment]
@shastri9999 
1. I do not see any use case for negative numbers, so for NUMBER itself we can have the validate starting from 0.
2. Its updated to textarea for address fields.

**Comment by shastri9999** [comment]
1. Phone numbers are validated now woth same logic as in Signup form
2. Negative numbers in number field don't get saved, prompts validation error on hitting save.

**Comment by shastri9999** [comment]
@suneelng A note , issue of not refreshing was due to following
GET /user/getusrdetails/action
GET /user/get/action

These are two API endpoints for same functionality, earlier getusrdetails was not present, only user/get/action was present and it was used. But this API doesn't return updated data while in same session, but gives updated value once logged out and logged in. To fix I changed it to getusrdetails, but we had no idea about changes in backend. So please do remove obsolete endpoints from swagger and everytime you update swagget just mention CHANGED in bold for API which gets changed.

**Comment by suneelng** [comment]
@shastri9999 
- Noted on the API change notification.
- Observed a side effect, the required fields are empty and the next button (during new broker application) will freeze the page as the attached screen shot.
- Missing timezone filed from the settings.


Screenshot:

![image](https://cloud.githubusercontent.com/assets/23191755/22615215/3f22cd60-eab6-11e6-95e3-48b60be869e7.png)

**Comment by shastri9999** [comment]
Can backend send not null values for answerDescription and send empty string?

**Comment by suneelng** [comment]
@shastri9999 
- Is it really needed to send empty string, this will have additional side effects on the status information for the user account. Quiet an effort on the back end. Let me know if there is a work around possible in the front end else i will look for a solution.

**Comment by shastri9999** [comment]
Checking for null has been added.
