### ISSUE TITLE
[firefox]: broker dashboard

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#23]
- Missing side menu collapse and expand icon.
- Scroll bar is not as per the design or according to chrome.
- Design issue - Right side bar
- Side menu collapse mode is not as per the design.

Screen Details:
1) Firefox
2) 1366x768

![user_image_17](https://cloud.githubusercontent.com/assets/23191755/21863321/fa53a340-d862-11e6-847d-5ae5a909f6f0.JPG)

![user_image_17](https://cloud.githubusercontent.com/assets/23191755/21863343/1173273a-d863-11e6-82c1-990e29fa5d34.PNG)

**Comment by shastri9999** [comment]
Side menu collapse and right side bar is fixed.

Mozilla Firefox doesn't allow styling of scrollbars , See this issue - https://bugzilla.mozilla.org/show_bug.cgi?id=77790. Alternatives are using a custom div to act as scroll bar which is not a recommended way anymore because it opens can of worms in other browsers and breaks compatibility on mobile. Even FB , Google, AirBnB and other sites as well leave firefox scrollbars as is.

**Comment by suneelng** [comment]
@shastri9999 
- Understand on the scroll bars.
- Messages and right appointments are hidden behind the block chain footer.

![image](https://cloud.githubusercontent.com/assets/23191755/22616728/ed4a2042-ead8-11e6-9861-ba50e04f94f1.png)

**Comment by shastri9999** [comment]
Added extra padding below for messages and appointments container.
