### ISSUE TITLE
OCR data truncation 

### ISSUE THREAD

**Issue by smilesikand** [shastri9999/kyck#7]
Browser: Chrome
Screen - 15.6"
Resolution - 1366 X 768

![ocrpreview](https://cloud.githubusercontent.com/assets/4374085/21807571/71ec329a-d765-11e6-9cd8-1a833308efb9.JPG)

**Comment by shastri9999** [comment]
@suneelng This is not possible unless backend says it to be displayed as text area. Also since length of field varies in different screen sizes, its not possible to determine if its cut.
Alternatively can display value as popup on hover which can show entire value. Let me know if alternate solution works

**Comment by shastri9999** [comment]
@suneelng To suggest alternative.

**Comment by suneelng** [comment]
@shastri9999,

- As discussed and tested, mouse hover is not displaying the full information.
- Re opening the issue for easier tracking.

**Comment by shastri9999** [comment]
@suneelng Please try with latest fix f2cde54.
The hover uses title attribute, which displays according to browser behaviour.
