### ISSUE TITLE
Document upload flow

### ISSUE THREAD

**Issue by smilesikand** [shastri9999/kyck#9]
Document flow modification:

1. User selects an image.
2. Image cropping tool
3. User crops the image.
4. Upload Image to server.

**Comment by suneelng** [comment]
@shastri9999 
- Sequence is fixed, there are few side effects.
- Can the message be changes to image is uploading than image is loading during upload action.
- The image preview is out of the modal window.
- Resolution: 1366x768, chrome
- the loading bar (screen loading) is always active when the page is refreshed when current page is pointing to document.

Snapshot
![image](https://cloud.githubusercontent.com/assets/23191755/22605390/a7fd1e12-ea75-11e6-824f-e55aa76b98c5.png)

![image](https://cloud.githubusercontent.com/assets/23191755/22605464/fe530e70-ea75-11e6-83b4-49b601b2841d.png)

(Loading Bar)
![image](https://cloud.githubusercontent.com/assets/23191755/22605486/10d5ee32-ea76-11e6-9677-32b6bdabba63.png)

**Comment by shastri9999** [comment]
Have changes the message, have clubbed issues of image preview with preview zoom in/zoom out.

**Comment by suneelng** [comment]
@shastri9999 
- Loding bar issue is still not fixed "http://ec2-52-77-245-236.ap-southeast-1.compute.amazonaws.com/#/app/document". If the above path is refreshed then the page loader always stays.
- The upload message is still not fixed.
Please clarify if these are fixed or will be fixed in another issue task.
